title: Evan Knapke
logo: "/images/knapke.png?raw=true"
description: Studying Computer Science at Ball State University
# markdown: kramdown
theme: jekyll-theme-minimal

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
